### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by akashdexati** [luqili/vultus#2]
@luqili @larryxuchen 

I have setup this project on anaconda. Downloaded caffe, dlib.

I am running the file in folder demoCode like below :
`vultus-master/demoCode$ python testBatchModel.py input.txt out/`

I am getting below error :
```
Traceback (most recent call last):
  File "testBatchModel.py", line 149, in <module>
    model = scipy.io.loadmat(BFM_path,squeeze_me=True,struct_as_record=False)
  File "/home/akash/anaconda3/envs/luqilivultus/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/akash/anaconda3/envs/luqilivultus/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable
```

Can you please suggest on probable changes.

Thanks

**Comment by akashdexati** [comment]
I resolved this
